#! /usr/bin/env python

from koan import utils
from pprint import pprint
import sys
import os

attributes = ["images", "profiles", "systems", "distros", "repos"]

def hook(what, name=None):
  try:
    if what[-1] == 's':
      data = getattr(xmlrpc_server, "get_%s"%what)()
    else:
      data = getattr(xmlrpc_server, "get_%s_as_rendered"%what)(name)
  except:
    traceback.print_exc()
    raise Exception("Cobbler Connection failure")
    sys.exit(2)
    
  return data

def list(what):
  if what not in attributes:
    raise Exception("I do not know what you play with!")
    sys.exit(2)
  _items = hook(what)
  print "what is it? %s"%what
  _alist = [ item['name'] for item in _items if 'name' in item ]
  return _alist

try:
  utils.setupLogging("koan")
except:
  pass

try:
  xmlrpc_server = utils.connect_to_server(server='server1.example.com', port=443)
  if not os.getuid() == 0:
    raise Exception("this operation requires root access")
    
  profiles = list('profiles')
  pprint(profiles)
  systems = list('systems')

  for system in systems:
    if system:
      item = hook('system', system)
    else:
      item = {}
    for key, value in item.items():
      if 'mac' in key: print "{ %s : %s }"%(key,value)

  distros = list('distros')
  pprint(distros)
  repos = list('repos')
  pprint(distros)
  images = list('images')
  pprint(images)

except Exception as detail:
  print '[ERROR] :', detail
